### ISSUE TITLE
Request to republish

### ISSUE THREAD

**Issue by kendrahavens** [nunit/dotnet-new-nunit#15]
Hey folks!

Earlier @jmarolf made PR #14 so that the NUnit template would open a class file by default upon initialization in Visual Studio. Now that the change is merged (thank you @halex2005!), we'd need you to republish the nuget reference for this project so we can pull it into new builds of the dotnet cli and then into Visual Studio.

Would that be possible?

Thank you!

**Comment by halex2005** [comment]
Yes, it is possible. I'll republish updated templates today.

**Comment by halex2005** [comment]
I've published new version 1.5.2 to nuget and added PR to [dotnet/cli](https://github.com/dotnet/cli/pull/9984)

**Comment by halex2005** [comment]
Nuget package published, PR https://github.com/dotnet/cli/pull/9984 merged, I'll close the issue.
