### ISSUE TITLE
Update to .NET Core 2.1

### ISSUE THREAD

**Issue by kendrahavens** [nunit/dotnet-new-nunit#16]
Hey folks,

Newer versions of the .NET Core templates default to .NET Core 2.1. If you'd like to update this one to 2.1 as well, that'd be great!

**Comment by rprouse** [comment]
Thanks for the update @kendrahavens. I'll get the code done tonight so it is ready for the next release.

**Comment by rprouse** [comment]
Update has been published to NuGet, https://www.nuget.org/packages/NUnit3.DotNetNew.Template/1.5.3

**Comment by kendrahavens** [comment]
Excellent! Thank you!
