### ISSUE TITLE
The F# Nunit Template for netcoreapp2.1 and netcoreapp2.2 are incorrect.

### ISSUE THREAD

**Issue by KevinRansom** [nunit/dotnet-new-nunit#26]
Hmm premature return there:

The dotnet cli, is still shipping updated release for netcoreapp2.2 and netcoreapp2.1.

The netcareapp2.2 templates package:  https://www.nuget.org/packages/NUnit3.DotNetNew.Template/1.6.0

Has the F# new template:
````
namespace Tests

open NUnit.Framework

[<TestClass>]
type TestClass () =

    [<SetUp>]
    member this.Setup () =
        ()

    [<Test>]
    member this.Test1 () =
        Assert.Pass()
````

The template should not have:
````
[<TestClass>]
type TestClass () =
````

````
This causes a build warning, it should be:
type TestClass () =
````
This has been corrected in the netcoreapp3.0 version of the templates.

Because of the package numbering you have done, I'm not sure how you If you could fix it and release an updated package, perhaps a 1.6.0.1 package.

Similarly if you could fix the F# netcoreapp 2.1 templates, in the 1.5.3 version of the package.

Thanks

Kevin

**Comment by halex2005** [comment]
Hi! Thanks for the feedback!

Sorry, I have no any knowledge about F# and what is wrong with current version of test class. Actually, I've started this project with C# support only and got contribution for F# and VB support in PR #1 and PR #20.

Actually, `[<TestClass>]` was removed from F# template at least in [v1.6.1](https://www.nuget.org/packages/NUnit3.DotNetNew.Template/1.6.1) after merging PR #20.
I didn't catch what I need to do now to fix your issue.
Could you update nunit templates with `dotnet new -i NUnit3.DotNetNew.Template`?
Or, could you provide pull request to fix F# template?

There is one template source for all versions of .NET Core and .NET Framework and I didn't see any way to add conditions to source code (except conditions in *.proj files).

I don't want to backport some patches to older versions of nunit templates. I recommend you update templates to latest version or remove that line with `[<TestClass>]` manually.

**Comment by halex2005** [comment]
I'll close this issue due to inactivity. Feel free to reopen issue if you have more feedback.
