### ISSUE TITLE
Move to NUnit?

### ISSUE THREAD

**Issue by rprouse** [nunit/dotnet-new-nunit#3]
@halex2005, great work on this, but the NUnit team is fielding issues on it. We would like to pull this into the NUnit project to ensure that it gets updated and maintained. It would be great if you could continue to lead the project and join the NUnit team, or we could take over if you prefer. All we ask is that you add a core team member to the NuGet feed so we have a backup and that you abide by our code of conduct.

What do you think?

**Comment by halex2005** [comment]
Hi, @rprouse. Yes, I can translate this project to nunit organization if I understand you correctly. And yes, I would like to continue update and maintain the project. I’ll try to add you to the nuget feed tomorrow.
Where I can read about your code of conduct? And how I can join the NUnit team?

**Comment by rprouse** [comment]
@halex2005 thanks. I have added you to the NUnit organization. Once we figure out how to transfer the repository, I will create a team for it and discuss adding you as the lead with the rest of the core team. I lead the NUnit organization aided by the core team. Each project, like yours, also has a team with a team lead. Or, that is what we strive for. In practice, I lead several projects and have team leads for a couple of the side projects. Depending on your interests, you are welcome to contribute in any area that you wish and if you would like to branch out and work on other NUnit projects, you will be welcome.

As for our code of conduct, it is at https://github.com/nunit/governance/blob/master/CODE_OF_CONDUCT.md. The TL;DR is "don't be a jerk" 😄

Once you accept the invitation, you can try to transfer this repository to the NUnit organization. If you don't have permissions, we will figure out how to do it. You might have to add me with sufficient permissions and I will transfer the repository.

My name is Rob Prouse and you can email me at rob@prouse.org. Could you send me an email so that I have your email address and can introduce you to the core team and tell them why I would like to bring your project into the organization?

**Comment by halex2005** [comment]
Just now I tried to transfer this repo to nunit organization, but unfortunately I got error "You don’t have the permission to create repositories on nunit".
@rprouse I just have invited you to this repository as collaborator, after accepting invitation I could give you admin rights and you could transfer repository to nunit organization, I though.

**Comment by rprouse** [comment]
I don't see the settings for this repo as a collaborator. Is there an option to make me an admin? If not, I could just fork the repository into the NUnit organization.

I have let the core team know you will be joining us.

**Comment by halex2005** [comment]
Rob, do you have accepted an invitation to collaborate?
I can make you an admin after you'll accept invitation.

![github-rob-status](https://user-images.githubusercontent.com/1401048/32458601-bc6f93ea-c34e-11e7-92ae-4e7d42ebdec7.png)

**Comment by rprouse** [comment]
Sorry about that, I thought I'd accepted. Done now.

**Comment by halex2005** [comment]
It seems that collaborators have only push to repository y access. I had transferred repository to @rprouse just now, please accept transfer and move repository to nunit.

**Comment by rprouse** [comment]
That worked, great idea.

@halex2005 welcome to the NUnit organization. You are the team lead for this project and you manage the direction and releases for this project. The @nunit/core-team is here to help you if you need it. The core team is myself, @jnm2, @CharliePoole, @OsirisTerje and @ChrisMaddock.

Our normal process is for all changes to go through Pull Requests and every pull request be reviewed by one other team member. For smaller side projects like this, we tend to be a bit easier on the rules, but pull requests are still a good idea.

I am planning a 3.9 release of NUnit this week. Once that is done, it would be nice to update this project with the newest versions of NUnit and the adapter. I can help with that.

Once again, welcome to NUnit.
