### ISSUE TITLE
Update to .NET Core 3.1 preview

### ISSUE THREAD

**Issue by kendrahavens** [nunit/dotnet-new-nunit#32]
Hey there!

We are pulling in templates to .NET Core 3.1 Preview. Could you publish targeting [.NET core 3.1 preview](https://dotnet.microsoft.com/download/dotnet-core)? 

Thank you!

**Comment by halex2005** [comment]
Hi, @kendrahavens! This task in process, see https://github.com/dotnet/core-sdk/pull/5335

**Comment by kendrahavens** [comment]
completed :)
