### ISSUE TITLE
Targeting .NET 5

### ISSUE THREAD

**Issue by kendrahavens** [nunit/dotnet-new-nunit#38]
Hello,

We have a slightly different versioning tag for .NET 5.
`netcoreapp5.0` should be `net5.0`

Best,
Kendra

**Comment by halex2005** [comment]
Hi! 
`net5.0` value wasn't worked for .net core 5.0 preview, CI checks was failed with that.
At least for 5.0.100-preview.1.20155.7 version which was public at the moment: https://github.com/nunit/dotnet-new-nunit/blob/master/appveyor.yml#L183

I'll fix TFM in #39.

**Comment by halex2005** [comment]
Done.

**Comment by kendrahavens** [comment]
Thank you!
