### ISSUE TITLE
dotnet new nunit -n "sample" is creating default project to .net5.0

### ISSUE THREAD

**Issue by jcbritobr** [nunit/dotnet-new-nunit#41]
I downloaded the latst template version for nunit and the command dotnet new nunit -n "sample" is creating default project to .net5.0

below my xml

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0"/>
  </ItemGroup>

</Project>
```

This is leading to missing assembly erros in projects.

**Comment by jnm2** [comment]
The samples usually need to be customized. Is this different from any other dotnet project template?

**Comment by jcbritobr** [comment]
> 
> 
> The samples usually need to be customized. Is this different from any other dotnet project template?

Using vscode I only need to pass the target framework with --framework, but this change broken visual studio template:
![image](https://user-images.githubusercontent.com/6579862/98305105-fbd16f80-1f9f-11eb-8cbb-620b00a272bb.png)
There is no way to change framework to netcore3.1. Only editing *.csproj by hand.

**Comment by halex2005** [comment]
Hi!
Yes, it is known, you can edit *.csproj manually for now.

This repository has been moved under support of .NET team to https://github.com/dotnet/test-templates
Moved project will be released with .NET 6.
I hope you can select target framework after release (btw .NET Framework will not be supported there).
