### ISSUE TITLE
Feature Request: Item Template templates

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/dotnet-new-nunit#8]
Inline with #7 - the templates I use most are the ones to create an individual TestFixture class.

I believe dotnet new can now also install item templates. If we go ahead with #7, I'd love for it to include TestFixture templates as well.

**Comment by rprouse** [comment]
I am good with this. Should we create a new templates team for our two templates repositories to make it easier for people to collaborate?

**Comment by ChrisMaddock** [comment]
I thought we already had one! Did you just make this now, or is it old? 😄 

https://github.com/orgs/nunit/teams/nunit-templates-team

**Comment by rprouse** [comment]
Forgot we had it, it sees so little traffic 😄

**Comment by halex2005** [comment]
Item Template has been added in PR #10. I propose to close this issue. #7 still opened and work-in-progress.

**Comment by ChrisMaddock** [comment]
I agree - awesome, thanks for adding them! 😄
